insert into Point (name, address) values ('Oberbrunner, Daniel and O''Connell', '8222 Barnett Center');
insert into Point (name, address) values ('Douglas, Gusikowski and Mayer', '4 Golf Place');
insert into Point (name, address) values ('Emard and Sons', '22342 Eagan Court');
insert into Point (name, address) values ('Paucek-Wolf', '3 Kensington Pass');
insert into Point (name, address) values ('Nolan, Thompson and Durgan', '532 Pennsylvania Drive');
insert into Point (name, address) values ('Smith, Kutch and Brakus', '580 Fisk Court');
insert into Point (name, address) values ('Stanton Group', '9477 Del Sol Point');
insert into Point (name, address) values ('Von Group', '70 Milwaukee Avenue');
insert into Point (name, address) values ('Ullrich-Cartwright', '3446 Sundown Street');
insert into Point (name, address) values ('Rau, McLaughlin and Muller', '62 Merrick Plaza');
insert into Point (name, address) values ('Stokes LLC', '01406 Shopko Trail');
